import { ArrowUpRight, BriefcaseBusiness, Check, Mail, MapPin, Phone, Sparkles, UserRound } from 'lucide-react'

const roles=[
  {role:'Customer Support VA | Shopify',company:'US-based client',date:'February 2026',copy:['Provided email and chat support alongside social media management.','Managed inboxes and customer communication with a reliable, helpful approach.']},
  {role:'Social Media Assistant',company:'Iskolar ng Bayan',date:'January 2026',copy:['Handled post scheduling, content planning, and caption writing.','Worked across Meta Business Suite, TikTok, and Instagram.']},
  {role:'Social Media Assistant',company:'Rcards',date:'September 2025 – December 2025',copy:['Supported social media post scheduling, content planning, and caption writing.','Prepared and coordinated content across Meta Business Suite, TikTok, and Instagram.']},
  {role:'Social Media & Admin Support | Sales Specialist',company:'Kippap Learning Corp.',date:'January 2024 – August 2025',copy:['Delivered timely support via email, chat, and phone, helping ensure high customer satisfaction.','Resolved product, billing, and account issues; reduced escalations through effective troubleshooting.','Guided customers on product features and best practices to improve adoption and experience.']},
  {role:'Social Media Assistant',company:'Project Padayon',date:'February 2024 – December 2024',copy:['Managed social media inquiries, engagement, and community interactions to strengthen brand presence.','Supported visibility and sales by promoting content, distributing marketing materials, and engaging leads.','Analyzed performance metrics and collaborated on campaigns to optimize reach and conversions.']},
]
const services=[
  ['Canva design','Branded social media graphics, marketing materials, and presentations.'],
  ['Email & chat support','Inbox management and clear, helpful customer communication.'],
  ['Social media management','Post scheduling, content planning, and caption writing across Meta Business Suite, TikTok, and Instagram.'],
  ['Admin & office tasks','Data entry, Excel reports, Google Sheets and Docs, and Microsoft Word formatting.'],
  ['Remote team collaboration','Effective day-to-day communication using Slack and Google Workspace.'],
]
const tools=['Canva Pro','Meta Business Suite','Slack','Gmail','Google Docs','Google Sheets','Facebook','TikTok','Instagram','Microsoft Excel','Microsoft Word','MS Office','Shopify','Google Workspace']

export default function AboutPage(){return <div id="about" className="about-page section-shell reveal"><header className="about-page-heading"><div className="eyebrow"><span/> ABOUT JOHN LLOYD</div><h1>Reliable support.<br/><em>Real care for the details.</em></h1><p>Virtual Assistant · Canva Pro · Email, Social Media & Admin Support Expert</p></header><section className="about-profile-card"><div className="about-profile-mark"><img src="/profile.jpg" alt="John Lloyd Laxamana"/><span>JL</span></div><div className="about-profile-copy"><div className="about-profile-top"><span className="experience-pill"><Sparkles size={14}/> 5+ YEARS OF EXPERIENCE</span><span className="reliable-line">Reliable <i/> Detail-oriented <i/> Tech-savvy</span></div><h2>Hi, I’m John Lloyd Laxamana.</h2><p>From designing eye-catching graphics in Canva to managing inboxes, resolving support tickets, and handling content posting across social media, I’m your go-to partner for high-quality, dependable virtual assistance.</p><div className="profile-contact"><a href="tel:+639100370145"><Phone size={15}/> +63 910 037 0145</a><a href="mailto:yourva.jl@gmail.com"><Mail size={15}/> yourva.jl@gmail.com</a></div></div></section>
    <section className="about-resume-grid"><div className="resume-main"><div className="about-section-title"><span><BriefcaseBusiness size={17}/></span><div><h2>Experience</h2><p>Customer care, social media, and everyday business support.</p></div></div><div className="experience-list">{roles.map((item,i)=><article className="experience-item" key={item.company+item.date}><div className="experience-marker"><span>{String(i+1).padStart(2,'0')}</span><i/></div><div className="experience-content"><div className="experience-heading"><div><h3>{item.role}</h3><b>{item.company}</b></div><time>{item.date}</time></div><ul>{item.copy.map(line=><li key={line}>{line}</li>)}</ul></div></article>)}</div>
        <div className="about-section-title service-title"><span><Sparkles size={17}/></span><div><h2>What I can do for you</h2><p>Practical, detail-minded help for the work behind your business.</p></div></div><div className="about-services-grid">{services.map(([title,copy],i)=><article className="about-service" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>
      </div><aside className="resume-side"><section className="about-note"><div className="about-section-title"><span><UserRound size={16}/></span><div><h2>About me</h2></div></div><p>I’m a highly experienced Virtual Assistant with over five years of proven success helping entrepreneurs, eCommerce brands, and remote teams streamline operations and deliver exceptional customer support.</p><p>If you’re looking for a professional, resourceful, and committed partner, I’d love to work with you. Let’s take your workload off your plate and your productivity to the next level.</p><a className="about-contact-link" href="mailto:yourva.jl@gmail.com">Let’s work together <ArrowUpRight size={14}/></a></section><section className="about-skills"><div className="about-section-title"><span><Check size={16}/></span><div><h2>How I work</h2></div></div><ul><li>Reliable and detail-oriented</li><li>Tech-savvy and resourceful</li><li>Clear, friendly communication</li><li>Committed to consistent support</li><li>Comfortable working remotely</li></ul></section><section className="about-tools"><div className="about-section-title"><span><Sparkles size={16}/></span><div><h2>Tools I use</h2></div></div><div className="about-tool-chips">{tools.map(tool=><span key={tool}>{tool}</span>)}</div></section><div className="about-availability"><span className="pulse"/> Available for remote work <MapPin size={14}/> Philippines</div></aside></section>
  </div>}
