import { useState } from 'react'
import { ArrowUpRight, X, Check } from 'lucide-react'
import { projects } from '../data/projects'
import BrandLogo from './BrandLogo'
const tagBrands={'Meta Business Suite':'meta','TikTok':'tiktok','Instagram':'instagram','Facebook':'facebook','Shopify':'shopify'}
function ProjectMark({project}){if(project.clientLogo)return <img className="project-client-image" src={project.clientLogo} alt={project.client+' logo'}/>;return project.clientMark==='shopify'?<BrandLogo brand="shopify" className="project-client-logo"/>:<span className="project-client-initials">{project.clientMark}</span>}
function ToolTag({label}){const brand=tagBrands[label];return <span className="project-tool-tag">{brand?<BrandLogo brand={brand}/>:label==='Email'?<b>@</b>:label==='Chat support'?<b>…</b>:label==='Phone support'?<b>☎</b>:null}{label}</span>}
function Preview({project}){return <div className={'preview preview-'+project.kind}>
{project.kind==='social'&&<><div className="preview-appbar"><span>◉</span><span>◉</span><span>♪</span><b>CONTENT CALENDAR</b><i>•••</i></div><div className="calendar"><div className="calendar-labels">{['MON','TUE','WED','THU','FRI'].map(x=><span key={x}>{x}</span>)}</div>{['A new week, a fresh start.','Behind the scenes','Your questions, answered','A little reminder to pause','This week at a glance'].map((x,i)=><div className="calendar-item" key={x}><b>0{i+1}</b><span className={'post-color color-'+i}>{['✳','◌','↗','✿','▧'][i]}</span><small>{x}</small></div>)}</div></>}
{project.kind==='admin'&&<><div className="doc-top"><span>▤</span><div><b>Weekly operations</b><small>Updated just now · Shared with team</small></div><button>Share</button></div><div className="doc-body"><div className="doc-sidebar"><i/><i/><i/><i/></div><div className="doc-content"><b>Everything in its place.</b><p>Weekly priorities and follow-ups</p><div className="doc-line long"/><div className="doc-line"/><div className="doc-task"><Check/> Review incoming requests <small>Complete</small></div><div className="doc-task"><Check/> Update shared tracker <small>Complete</small></div><div className="doc-task faint">○ Prepare next week’s notes <small>Up next</small></div></div></div></>}
{project.kind==='enrollment'&&<div className="enrollment-deck"><div className="enrollment-rail"><span className="enroll-monogram">K</span><i className="rail-active"/><i/><i/><i/></div><div className="enrollment-main"><div className="enroll-topline"><span>LEARNER SUPPORT</span><span className="enroll-status"><i/> HERE TO HELP</span></div><h4>Every step to<br/>getting started.</h4><p>Enrollment guidance and portal access support for learners.</p><div className="enroll-progress"><span>ENROLLMENT JOURNEY</span><div><i/><i/><i/></div><small>Enrollment <b>›</b> Portal access <b>›</b> Ready to learn</small></div><div className="enroll-bottom"><div><b>01</b><span>ENROLLMENT<br/>PROCESS</span></div><div><b>02</b><span>PORTAL<br/>ACCESS</span></div><div className="enroll-social"><b>✳</b><span>SOCIAL CONTENT<br/>& COMMUNITY</span></div></div></div></div>}
{project.kind==='support'&&<><div className="inbox-head"><span>INBOX OVERVIEW</span><b>Today <i>⌄</i></b></div><div className="inbox-stats"><div><small>OPEN CONVERSATIONS</small><b>08</b></div><div><small>REPLIED TODAY</small><b>24 <i>↑</i></b></div></div>{[['AM','Order update request','Thanks for getting back to me so quickly…','2m','peach'],['JL','Product availability','Happy to help you find the right option…','18m','blue']].map(x=><div className="message-row" key={x[1]}><span className={'initial '+x[4]}>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><em>{x[3]}</em></div>)}</>}
{project.kind==='shopify'&&<><div className="shop-head"><span className="shop-bag">S</span><div><b>Store overview</b><small>Tuesday, 14 October</small></div><span className="live-pill">● LIVE</span></div><div className="shop-metrics"><div><small>TOTAL ORDERS</small><b>128 <i>↗ 12%</i></b></div><div><small>PRODUCTS</small><b>46 <i>Active</i></b></div></div><div className="order-list"><span>RECENT ORDERS</span>{['#1048  ·  Maya C.','#1047  ·  Alex R.','#1046  ·  Sam T.'].map((x,i)=><div key={x}>{x}<small className={i===0?'status-new':'status-done'}>{i===0?'Processing':'Fulfilled'}</small></div>)}</div></>}
{project.kind==='content'&&<div className="content-collage"><div className="post-tile post-one"><span>THE EVERYDAY EDIT</span><b>Little moments,<br/>made brighter.</b><i>✳</i></div><div className="post-tile post-two"><span>STUDIO NOTES · 04</span><b>Make room<br/>for good things.</b><i>◌</i></div><div className="post-tile post-three"><i>✿</i><b>A softer<br/>kind of Sunday.</b></div></div>}
{project.kind==='workflow'&&<><div className="flow-head"><span>✳ DAILY FLOW</span><b>Everything has a place.</b></div><div className="flow-steps">{[['01','Team messages','Slack'],['02','Content queue','Meta Suite'],['03','Customer inbox','Gmail'],['04','Weekly tracker','Sheets']].map((x,i)=><div className="flow-step" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small>{i<3&&<i/>}</div>)}</div><div className="flow-foot">Connected by a thoughtful daily rhythm <span>↗</span></div></>}
</div>}
export default function Projects(){const[selected,setSelected]=useState(null);return <><section id="projects" className="section-shell content-section reveal"><div className="section-heading"><div><div className="eyebrow"><span/> PROJECTS & EXPERIENCE</div><h2>Selected work, built around people<span className="accent-dot">.</span></h2></div><p>Social media, customer support, and Shopify work from Kippap Learning Corp., Iskolar ng Bayan, Rcards, Project Padayon, and a US-based client.</p></div><div className="project-grid">{projects.map(p=><button key={p.id} className="project-card" onClick={()=>setSelected(p)}><Preview project={p}/><div className="project-meta"><div className="project-client"><ProjectMark project={p}/><span>{p.client}</span></div><i><ArrowUpRight size={17}/></i></div><div className="project-category">{p.category}</div><h3>{p.title}</h3><p>{p.description}</p><div className="project-date">{p.date}</div><div className="tag-row">{p.tags.map(t=><ToolTag key={t} label={t}/>)}</div></button>)}</div><div className="project-footnote"><span>↗</span> Select a project to explore the details</div></section>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="project-modal" role="dialog" aria-modal="true" aria-label={selected.title} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close project"><X/></button><Preview project={selected}/><div className="modal-copy"><div className="modal-project-brand"><ProjectMark project={selected}/><div><div className="eyebrow"><span/>{selected.client} · {selected.date}</div><h2>{selected.title}</h2></div></div><p>{selected.detail}</p><div className="tag-row">{selected.tags.map(t=><ToolTag key={t} label={t}/>)}</div></div>{selected.gallery&&<section className="project-gallery" aria-label="Rcards project images"><div className="gallery-heading"><h3>Rcards project samples</h3><span>7 IMAGES</span></div><div className="gallery-grid">{selected.gallery.map((src,i)=><figure key={src}><img src={src} alt={'Rcards project sample '+(i+1)} loading="lazy"/><figcaption>Sample {String(i+1).padStart(2,'0')}</figcaption></figure>)}</div></section>}</article></div>}</>}
