import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import './brand.css'
import './redesign.css'
import './about-page.css'
import './content-update.css'
import './project-decks.css'
import './intro.css'
import './about-shapes.css'
import './theme.css'
createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>)
